#pragma once

// TODO: Wrap in name space.
extern "C" {
    #include <metis.h>
}

#define TENSORS_HAS_METIS

namespace Tensors
{
    namespace Sparse
    {
        template<IntQ Int, Parallel_T parQ, bool base = 0>
        class Metis
        {
        public:
            
            // Default constructor
            Metis() = default;
            
            // Since we declare no user-defined destructor, suitable copy constructor, copy assignment, move constructor, and copy assignment will be generated by compiler.
            
            
            template<IntQ I_1, IntQ I_2, IntQ I_3, IntQ I_4>
            Permutation<Int,parQ> operator()(
                mptr<I_1> rp_, mptr<I_2> ci_, const I_3 n_, const I_4 final_thread_count = 1
            )
            {
                // Computes a nested dissection reordering of _symmetric_ sparsity pattern, rp, ci.
                // n  = number of rows = number of columns
                // rp = rowpointers: An increasing array of integers of size n+1 starting at 0. Last entry is number of nonzeroes.
                // ci = columnindices: An array of length rp[n].
                // ci[rp[i]],...,ci[rp[i+]] are the column indices of the i-th row.
                
            
                // TODO: Do a symmetrization if needed?
                
                TOOLS_PTIMER(timer,ClassName()+"::operator()");

                idx_t n = int_cast<idx_t>(n_);
                
                Tensor1<idx_t,idx_t> rp    ( int_cast<idx_t>( n + 1  ) );
                Tensor1<idx_t,idx_t> ci    ( int_cast<idx_t>( rp_[n] ) );
                Tensor1<idx_t,idx_t> perm  ( int_cast<idx_t>( n      ) );
                Tensor1<idx_t,idx_t> iperm ( int_cast<idx_t>( n      ) );
                
                idx_t nnz_counter = 0;
                
                rp[0] = 0;
                
                // TODO: This could be parallelized, but I don't think that there is a need for this.
                
                if( !std::in_range<idx_t>(rp_[n]) )
                {
                    eprint(ClassName()+"::operator(): row pointers do not fit into type " + TypeName<idx_t> + " .");
                }
                
                // We need to discard the diagonal entries.
                for( idx_t i = 0; i < n; ++i )
                {
                    const idx_t k_begin = static_cast<idx_t>(rp_[i    ]);
                    const idx_t k_end   = static_cast<idx_t>(rp_[i + 1]);
                    
                    for( idx_t k = k_begin; k < k_end; ++k )
                    {
                        const idx_t j = static_cast<idx_t>(ci_[k]) - base;
                        
                        if( i != j )
                        {
                            ci[nnz_counter] = j;
                            ++nnz_counter;
                        }
                    }
                    
                    rp[i+1] = nnz_counter;
                }

                (void)METIS_NodeND(
                    &n, rp.data(), ci.data(), nullptr, nullptr, perm.data(), iperm.data()
                );

                return Permutation<Int,parQ>( perm.data(), n, Inverse::False, Int(final_thread_count) );
            }
            
        public:
            
            static std::string ClassName()
            {
                return std::string("Metis")+ "<" + TypeName<Int> + "," + Tools::ToString(base) + ">";
            }
            
        }; // class Metis
    
    } // namespace Sparse

} // namespace Tensors
