#pragma once

namespace Tensors
{
    // TODO: It could be helpful to track min and max of the two containers as these might be needed for a later assembly.
    
    template<typename T_0, typename T_1, typename Int>
    class alignas(ObjectAlignment) PairAggregator final
    {
        static_assert(IntQ<Int>,"");

        using Container_0_T = Tensor1<T_0,Int>;
        using Container_1_T = Tensor1<T_1,Int>;

        mutable Int current_size = Int(0);
        mutable Int capacity     = Int(1);
        
        mutable Container_0_T container_0 {capacity};
        mutable Container_1_T container_1 {capacity};

    public:

        explicit PairAggregator( const Int n )
        :   current_size ( Int(0)  )
        ,   capacity     ( Ramp(n) )
        ,   container_0  ( Ramp(n) )
        ,   container_1  ( Ramp(n) )
        {}

        // Default constructor
        PairAggregator() = default;
        
        // Since we declare no user-defined destructor, suitable copy constructor, copy assignment, move constructor, and copy assignment will be generated by compiler.

        Int Size() const
        {
            return current_size;
        }
        
        void Clear()
        {
            current_size = Int(0);
        }
        
        TOOLS_FORCE_INLINE void Push( cref<T_0> a_0, cref<T_1> a_1 )
        {
            if( current_size >= capacity ) { Expand(); }

            container_0[current_size] = a_0;
            container_1[current_size] = a_1;
            ++current_size;
        }
        
        TOOLS_FORCE_INLINE 
        void Push( T_0 && a_0, T_1 && a_1 )
        {
            if( current_size >= capacity ) { Expand(); }

            container_0[current_size] = std::move(a_0);
            container_1[current_size] = std::move(a_1);
            ++current_size;
        }
        
        Container_0_T Disband_0()
        {
            ShrinkToFit();
            return std::move(container_0);
        }
        
        Container_1_T Disband_1()
        {
            ShrinkToFit();
            return std::move(container_1);
        }
        
        // A bit dangerous, this is. But since we do not use any buffering, this might work.
        mptr<T_0> data_0()
        {
            return container_0.data();
        }
        
        cptr<T_0> data_0() const
        {
            return container_0.data();
        }

        mptr<T_1> data_1()
        {
            return container_1.data();
        }
        
        cptr<T_1> data_1() const
        {
            return container_1.data();
        }

    public:

        Int Capacity() const
        {
            return capacity;
        }
        
        void RequireCapacity( const Int new_capacity ) const
        {
            if( new_capacity > capacity)
            {
                SetCapacity( new_capacity );
            }
        }
        
        void SetCapacity( const Int new_capacity ) const
        {
            TOOLS_PTIMER(timer,MethodName("SetCapacity"));
            
#ifdef TENSORS_ALLOCATION_LOGS
            TOOLS_LOGDUMP(capacity);
            TOOLS_LOGDUMP(new_capacity);
#endif
            
            Container_0_T new_container_0 (new_capacity);
            Container_1_T new_container_1 (new_capacity);
            
            const Int s = Min( capacity, new_capacity );
            
            std::move(
                container_0.data(),
                container_0.data(s),
                new_container_0.data()
            );
            std::move(
                container_1.data(),
                container_1.data(s),
                new_container_1.data()
            );
            
            using std::swap;
            swap( container_0, new_container_0 );
            swap( container_1, new_container_1 );
            
            capacity = new_capacity;
        }
        
        void ShrinkToFit()
        {
            if( capacity > current_size )
            {
                SetCapacity(current_size);
            }
        }
        
    protected:
        
        void Expand() const
        {
            SetCapacity( Int(2) * capacity );
        }
        
    public:
        
        static std::string MethodName( const std::string & tag )
        {
            return ClassName() + "::" + tag;
        }
        
        static std::string ClassName()
        {
            return std::string("PairAggregator")+"<"+TypeName<T_0>+","+TypeName<T_1>+","+TypeName<Int>+">";
        }
    };
    
} // namespace Tensors
